### ISSUE TITLE
ModuleNotFoundError: No module named 'Bot'

### ISSUE THREAD

**Issue by praneethpj** [nimeshabuddhika/Tensorflow-Chatbot#2]
Hi, I am really interested in your project.  When I am trying to run this project this error is displayed. Please can you suggest me any solution

Traceback (most recent call last):
  File "cli.py", line 1, in <module>
    from Bot import ChatBot as bot
ModuleNotFoundError: No module named 'Bot'

**Comment by praneethpj** [comment]
> 
> 
> Hi, I am really interested in your project. When I am trying to run this project this error is displayed. Please can you suggest me any solution
> 
> Traceback (most recent call last):
> File "cli.py", line 1, in
> from Bot import ChatBot as bot
> ModuleNotFoundError: No module named 'Bot'

I solved it. The problem with path.py

**Comment by ory123** [comment]
Hey !
When I am trying to run train.py it gives an error called no module named Bot.
Please can you suggest how you solved this error

**Comment by nerkdesign** [comment]
Hi, sorry to come back on you issue, I got the same and I can't figure out where the issue is on path.py, would you mind to give more info ? what's missing ? how to correct it ? thanks

**Comment by laurentjuma** [comment]
move cli.py into the Bot folder and just "import ChatBot as bot" instead of  "from Bot import ChatBot as bot"
