### ISSUE TITLE
Error on reponse

### ISSUE THREAD

**Issue by nerkdesign** [nimeshabuddhika/Tensorflow-Chatbot#5]
Hi,

I have an issue when no response:
Traceback (most recent call last):
  File "cli.py", line 11, in <module>
    print("A : "+ob.response(text))
TypeError: Can't convert 'NoneType' object to str implicitly

Could you help me with that ?

Thanks

**Comment by psynyde** [comment]
```
if ob.response(text) == None:
        print("Sry i couldn't understand that")
```
add this after close if statement it should work fine

**Comment by nerkdesign** [comment]
Hi thanks for this feedback. Finally I did this :

    if ob.response(text) == None:
        print("A : No result")
    else :
        print("A : "+ob.response(text))

But it strange that sometime the chat say "I don't know" and sometimes "null"

I close this incident.
